Update botssh

diff --git a/Modulos/botssh b/Modulos/botssh
--- a/Modulos/botssh
+++ b/Modulos/botssh
@@ -1,3 +1,7 @@
+<<<<<<< HEAD
+# Auto detect text files and perform LF normalization
+* text=auto
+=======
 #!/bin/bash
 clear
 fun_bar () {
@@ -30,12 +34,12 @@ tput cnorm
 fun_botOnOff () {
       [[ $(ps x | grep "bot_plus"|grep -v grep | wc -l) = '0' ]] && {
           clear
-          echo -e "\E[44;1;37m             ⚙️🛠🟥BOT DK-SSH INSTALLER⚙️🛠🟥          \E[0m\n"
+          echo -e "\E[44;1;37m             🛠🟥BOT DK-SSH INSTALLER⚙️🛠🟥               \E[0m\n"
           echo -ne "\033[1;32mINFORM YOUR TOKEN:\033[1;37m "; read tokenbot
   	    echo ""
-  	    echo -ne "\033[1;32mINFORM YOUR ID:\033[1;37m "; read iduser
+  	    echo -ne "\033[1;32m⚙️🛠INFORM YOUR ID:\033[1;37m "; read iduser
           clear
-          echo -e "\033[1;32mSTARTING DK-SSH BOT \033[0m\n"
+          echo -e "\033[1;32m⚙️🛠STARTING DK-SSH BOT \033[0m\n"
           fun_bot1 () {
   	        [[ ! -e "/etc/SSHPlus/ShellBot.sh" ]] && wget -qO- https://raw.githubusercontent.com/shellscriptx/shellbot/master/ShellBot.sh > /etc/SSHPlus/ShellBot.sh
   	        cd /etc/SSHPlus
@@ -50,12 +54,12 @@ fun_botOnOff () {
   	        cd $HOME
           }
           fun_bar 'fun_bot1'
-          [[ $(ps x | grep "bot_plus"|grep -v grep | wc -l) != '0' ]] && echo -e "\n\033[1;32m DK-KSSH BOT ON !\033[0m" || echo -e "\n\033[1;31m ERROR! RE-ANALYZE YOUR INFORMATION\033[0m"
+          [[ $(ps x | grep "bot_plus"|grep -v grep | wc -l) != '0' ]] && echo -e "\n\033[1;32m 🟥⚙️🛠DK-SSH BOT ON ⚙️🛠🟥 !\033[0m" || echo -e "\n\033[1;31m ERROR! RE-ANALYZE YOUR INFORMATION\033[0m"
           sleep 3
           menu
       } || {
           clear
-          echo -e "\033[1;32m⚙️🛠🟥STOPPING BOT DK-SSH⚙️🛠🟥 ... \033[0m\n"
+          echo -e "\033[1;32m🛠🟥BOT DK-SSH INSTALLER⚙️🛠🟥 ... \033[0m\n"
           fun_bot2 () {
               screen -r -S "bot_plus" -X quit
               screen -wipe 1>/dev/null 2>/dev/null
@@ -66,18 +70,18 @@ fun_botOnOff () {
               sleep 1
           }
           fun_bar 'fun_bot2'
-          echo -e "\n\033[1;32m \033[1;31m⚙️🛠🟥DK-SSH BOT STOPPED⚙️🛠🟥! \033[0m"
+          echo -e "\n\033[1;32m \033[1;31m🛠🟥BOT DK-SSH INSTALLER⚙️🛠🟥! \033[0m"
           sleep 3
           menu
       }
 }
 
 fun_instbot () {
-echo -e "\E[44;1;37m             💎⚙️🛠🟥DK-SSH BOT MANAGER⚙️🛠🟥💎             \E[0m\n"
+echo -e "\E[44;1;37m             🛠🟥BOT DK-SSH INSTALLER⚙️🛠🟥             \E[0m\n"
 echo -e "                 \033[1;33m[\033[1;31m!\033[1;33m] \033[1;31mATTENTION \033[1;33m[\033[1;31m!\033[1;33m]\033[0m"
 echo -e "\n\033[1;32m1° \033[1;37m- \033[1;33mBY YOUR TELEGRAM ACCESS THE FOLLOWING BOT\033[1;37m:\033[0m"
-echo -e "\n\033[1;32m2° \033[1;37m- \033[1;33mBOT \033[1;37m@BotFather \033[1;33m⚙️CREATE YOUR BOT \033[1;31mOPTION: \033[1;37m/newbot\033[0m"
-echo -e "\n\033[1;32m3° \033[1;37m- \033[1;33mBOT \033[1;37m@my_id_bot \033[1;33m⚙️AND GET YOUR ID \033[1;31mOPTION: \033[1;37m/id\033[0m"
+echo -e "\n\033[1;32m2° \033[1;37m- \033[1;33mBOT \033[1;37m@BotFather \033[1;33mCREATE YOUR BOT \033[1;31mOPTION: \033[1;37m/newbot\033[0m"
+echo -e "\n\033[1;32m3° \033[1;37m- \033[1;33mBOT \033[1;37m@my_id_bot \033[1;33mAND GET YOUR ID \033[1;31mOPTION: \033[1;37m/id\033[0m"
 echo -e "\033[0;34m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[1;32m"
 echo ""
 read -p "DESEJA CONTINUAR ? [s/n]: " -e -i n resposta
@@ -91,18 +95,4 @@ fi
 }
 [[ -f "/etc/SSHPlus/ShellBot.sh" ]] && fun_botOnOff || fun_instbot
 #fim
-
-    © 2021 GitHub, Inc.
-    Terms
-    Privacy
-    Security
-    Status
-    Docs
-
-    Contact GitHub
-    Pricing
-    API
-    Training
-    Blog
-    About
-
+>>>>>>> e6b4f80bd6fd084d555c3919240364895b0b939d
